port=11000
catalog.port=11001
test.execution.mode=docker
external.hostname=directstream
config.service.url=http://unused
cache.offset.ranges.expiration.seconds=10
config.provider=properties
config.sources=dummyapi
config.source.dummyapi.s3key=dummyapi
config.source.dummyapi.s3secret=dummysecret
config.source.dummyapi.bootstrap.servers=kafka1:9092
config.source.dummyapi.schema.registry.schema.registry.url=http://schema-registry:8081/
#ssk.ssl.enabled=true
#ssk.keystore.path=/home/roman/code/directstream/etc/keystore.jks
#ssk.keystore.password=password
#isk.ssl.enabled=true
#isk.keystore.path=/home/roman/code/directstream/etc/keystore.jks
#isk.keystore.password=password