bootstrap.servers=kafka1:10092
security.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="unrestricted" password="unrestricted-secret";

ranges.topic.name=_streambased_ranges
board.size=1000
use.schema.registry=true
schema.registry.schema.registry.url=http://schema-registry:8081
schema.registry.json.fail.invalid.schema=false

consumer.group.id=Streambased-Indexer
kafkacache.topic.replication.factor=1

aggregate.maxRecordToReturn=1000000

# ---------- Indexing Configuration --------------- #

field.extractors=transactionsExtractor,payment_termsExtractor

field.extractors.transactionsExtractor.class=io.streambased.index.extractor.JsonValueFieldsExtractor
field.extractors.transactionsExtractor.topic=transactions
field.extractors.transactionsExtractor.useSchemaRegistry=true

field.extractors.payment_termsExtractor.class=io.streambased.index.extractor.JsonValueFieldsExtractor
field.extractors.payment_termsExtractor.topic=payment_terms
field.extractors.payment_termsExtractor.useSchemaRegistry=true