log4j.rootLogger=WARN

io.trino=INFO

io.trino.plugin.kafka=INFO

# show classpath for plugins
io.trino.server.PluginManager=WARN

# Maven plugin loading code
com.ning.http.client=WARN
org.apache.kafka=WARN

#org.apache.kafka.clients.consumer.internals=DEBUG
# -Dorg.apache.logging.log4j.level=DEBUG