  spark-iceberg:
    image: tabulario/spark-iceberg:3.5.5_1.8.1
    hostname: spark
    container_name: spark-iceberg
    volumes:
      - ./spark/warehouse:/home/iceberg/warehouse
      - ./spark/notebooks:/home/iceberg/notebooks/notebooks
      - ./spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./spark/bin/entrypoint.sh:/opt/spark/entrypoint.sh
    environment:
      - AWS_ACCESS_KEY_ID=dummyapi
      - AWS_SECRET_ACCESS_KEY=dummysecret
      - AWS_REGION=us-east-1
    ports:
      - 7077:7077
      - 8888:8888
      - 10000:10000
      - 10001:10001
      - 4040-4050:4040-4050
      - 15002:15002
      - 8180:8180

  directstream:
    image: streambased/directstream:demo
    hostname: directstream
    container_name: directstream
    platform: linux/amd64
    depends_on:
      - shadowtraffic
    restart: on-failure
    volumes:
      - "./directstream/etc/directstream-config.json:/app/etc/directstream-config.json"
      - "./directstream/etc/indexer.properties:/app/etc/indexer.properties"
      - "./directstream/etc/logback.xml:/app/etc/logback.xml"
    ports:
      - 11000:11000
      - 11001:11001

  s3manager:
    image: cloudlena/s3manager
    hostname: s3manager
    container_name: s3manager
    platform: linux/amd64
    depends_on:
      - directstream
    restart: on-failure
    ports:
      - 9180:9180
    environment:
      - ACCESS_KEY_ID=dummyapi
      - SECRET_ACCESS_KEY=dummysecret
      - REGION=us-east-1
      - USE_SSL=false
      - PORT=9180
      - ENDPOINT=directstream:11000

