board.size=1000
use.schema.registry=true

consumer.group.id=Streambased-Indexer
kafkacache.topic.replication.factor=1

aggregate.maxRecordToReturn=1000000

index.storage.type=LUCENE
index.directory=/tmp

sources=streambased

sources.streambased.bootstrap.servers=kafka1:9092
sources.streambased.schema.registry.schema.registry.url=http://schema-registry:8081
sources.streambased.schema.registry.json.fail.invalid.schema=false