version: '3.7'
services:

#  streambased-server:
#    image: streambased/streambased-enterprise:latest
#    hostname: streambased-server
#    platform: linux/amd64
#    ports:
#      - '8080:8080'
#    volumes:
#      - type: bind
#        source: "./serverConfig"
#        target: /etc/streambased/etc
#        read_only: true
#    command: >
#      sh -c "java -Dconfig=etc/config.properties -Djdk.attach.allowAttachSelf=true -Dfile.encoding=UTF-8 -Dlog.levels-file=/etc/streambased/etc/log.properties io.streambased.server.StreambasedServer"

  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset
    platform: linux/amd64
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@superset.com
      - ADMIN_PASSWORD=admin
    ports:
      - '8088:8088'

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    container_name: jupyter
    platform: linux/amd64
    command: sleep infinity
    ports:
      - '8888:8888'
    volumes:
      - type: bind
        source: "./notebooks"
        target: /notebooks
        read_only: false

  kafka-client:
    build:
      context: ./kafka-client
      dockerfile: Dockerfile
    container_name: kafka-client
    platform: linux/amd64