FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
}

ENABLE_PROXY_FIX = True
SECRET_KEY = "YOUR_OWN_RANDOM_GENERATED_STRING"

FAB_ADD_SECURITY_API = True

WTF_CSRF_ENABLED = False

MAPBOX_API_KEY = 'pk.eyJ1IjoidG9tLXN0cmVhbWJhc2VkIiwiYSI6ImNsdzZrcWt4NjFxaWEyam9jMGlxanFnZTkifQ.2CCvcIQu0JyxBAclJmFprg'