version: '3.7'
services:

  streambased-server:
    image: streambased/streambased-enterprise:latest
    hostname: streambased-server
    platform: linux/amd64
    ports:
      - '8080:8080'
    volumes:
      - type: bind
        source: "./serverConfig"
        target: /etc/streambased/etc
        read_only: true

  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset
    platform: linux/amd64
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@superset.com
      - ADMIN_PASSWORD=admin
    ports:
      - '8088:8088'
